USE ROLE SYSADMIN;

CREATE DATABASE POWER_HOUR;

CREATE OR REPLACE TABLE PUBLIC.FAV_PET 
    (
      ID INTEGER NOT NULL AUTOINCREMENT
    , PET STRING
);

SELECT * FROM FAV_PET;
SELECT PET , COUNT(1) AS NO_OF_PICKS FROM FAV_PET GROUP BY PET ORDER BY COUNT(1) DESC;

CREATE OR REPLACE TABLE PUBLIC.ANSWERS 
    (
         ID INTEGER NOT NULL AUTOINCREMENT
        ,NAME STRING
        ,AGE INT
        ,NO_DOGS INT
        ,NO_CATS INT
        ,NO_BIRDS INT
        ,NO_FISH INT
        ,NO_REPTILES INT
        ,GENDER STRING
    );

SELECT * FROM ANSWERS;